<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-tss-add-another-field tvd-center-align">
    <a href="javascript:void(0)">
		<i><?php echo dashboard_icon( 'plus-circle-regular' ) ?></i>
        <span><?php _e( 'Add Another Field', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
    </a>
</div>
