<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-tss-field-data">
	<span><?php echo __( 'Field Value', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
	<div class="tvd-input-field">
		<input id="tvd-tss-field-location" class="input-change" type="text" value="<#= model.get('data').location ? model.get('data').location : '' #>"
		       data-field="data_location" placeholder="<?php echo __( 'e.g New York', TVE_DASH_TRANSLATE_DOMAIN ) ?>">
		<label for="tvd-tss-field-text"><?php echo __( 'Location', TVE_DASH_TRANSLATE_DOMAIN ) ?></label>
	</div>

	<div id="tvd-tss-google-map">

	</div>
</div>
