<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Delete', TVE_DASH_TRANSLATE_DOMAIN ) ?> <strong><#= model.get('name') #></strong> - <#= model.get('type') ? 'Field' : 'Group' #></h3>
	<p><?php echo __( 'You are about to permanently delete the  ', TVE_DASH_TRANSLATE_DOMAIN ) ?> <#= model.get('type') ? 'field' : 'group' #> <#= model.get('name') #>. <?php echo __( 'Are you sure you want to delete it ?', TVE_DASH_TRANSLATE_DOMAIN ) ?> ? </p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( 'No', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn tvd-btn-red tvd-waves-light tvd-right tvd-delete-item">
				<?php echo __( 'Yes', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
	</div>
</div>

