<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Edit Group', TVE_DASH_TRANSLATE_DOMAIN ) ?></h3>
	<p><?php echo __( 'Edit field group', TVE_DASH_TRANSLATE_DOMAIN ) ?></p>
	<div class="tvd-v-spacer"></div>
	<div class="tvd-tss-flex">
        <div class="tvd-input-field">
            <input  style="margin-left: 77px" id="tvd-tss-group-name" type="text" value="<#= model.get('name') #>" data-field="name" placeholder="<?php echo __( 'Group name', TVE_DASH_TRANSLATE_DOMAIN ) ?>">
            <label for="tvd-tss-group-name"><?php echo __( 'Group Name', TVE_DASH_TRANSLATE_DOMAIN ) ?></label>
        </div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-tss-flex tvd-tss-space-between">
        <a href="javascript:void(0)"
           class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
            <?php echo __( 'Cancel', TVE_DASH_TRANSLATE_DOMAIN ) ?>
        </a>
        <a href="javascript:void(0)"
           class="tvd-btn tvd-btn-green tvd-waves-light tvd-right tvd-modal-submit">
            <?php echo __( 'Save', TVE_DASH_TRANSLATE_DOMAIN ) ?>
        </a>
	</div>
</div>
