<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="tvd-modal-content tvd-tss-add">
    <h3 class="tvd-modal-title"><?php echo __( 'New Group', TVE_DASH_TRANSLATE_DOMAIN ) ?></h3>
	<hr>
    <div class="tvd-tss-flex">
		<?php _e( 'Field group', TVE_DASH_TRANSLATE_DOMAIN ) ?>: <#= group.get('name') #>
    </div>

    <div class="tvd-tss-fields-wrapper"></div>
    <div class="tvd-tss-fields-add-more"></div>

    <div class="tvd-modal-footer">
        <div class="tvd-tss-flex tvd-tss-space-between">
            <a href="javascript:void(0)"
               class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
                <?php echo __( 'Cancel', TVE_DASH_TRANSLATE_DOMAIN ) ?>
            </a>
            <a href="javascript:void(0)"
               class="tvd-btn tvd-btn-green tvd-waves-light tvd-right tvd-tss-save-field">
                <?php echo __( 'Save', TVE_DASH_TRANSLATE_DOMAIN ) ?>
            </a>
        </div>
    </div>
</div>

