<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<nav class="tvd-nav">
    <ul>
        <li>
            <a href="javascript:void(0)">
                <?php _e( 'Smart Tracking', TVE_DASH_TRANSLATE_DOMAIN ); ?>
            </a>
        </li>
        <li class="active">
            <a href="#global_fields">
                <?php _e( 'Smart Content', TVE_DASH_TRANSLATE_DOMAIN ); ?>
                <i class="tvd-icon-expanded tvd-no-margin-right"></i>
            </a>
        </li>
        <li>
            <a href="#smart_complete">
                <?php _e( 'Smart Complete', TVE_DASH_TRANSLATE_DOMAIN ); ?>
            </a>
        </li>
    </ul>
</nav>



