CREATE TABLE `wp_hfcm_scripts` (  `script_id` int(10) NOT NULL AUTO_INCREMENT,  `name` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `snippet` text COLLATE utf8mb4_unicode_520_ci,  `device_type` enum('mobile','desktop','both') COLLATE utf8mb4_unicode_520_ci DEFAULT 'both',  `location` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `display_on` enum('All','s_pages','s_posts','s_categories','s_custom_posts','s_tags','latest_posts','manual') COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'All',  `lp_count` int(10) DEFAULT NULL,  `s_pages` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `ex_pages` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `s_posts` varchar(1000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `ex_posts` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `s_custom_posts` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `s_categories` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `s_tags` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `status` enum('active','inactive') COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'active',  `created_by` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `last_modified_by` varchar(300) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `created` datetime DEFAULT NULL,  `last_revision_date` datetime DEFAULT NULL,  PRIMARY KEY (`script_id`)) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_hfcm_scripts` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_hfcm_scripts` VALUES('1', 'CopeCart Upsell Script - Header', '<script src=\"//copecart.com/cdn/v1/upsell.js\"></script>\r\n', 'both', 'header', 's_pages', '5', '[2305]', '[]', '[]', '[]', '[]', '[]', '[]', 'inactive', 'Juliusmiribung', NULL, '2020-01-13 08:26:08', NULL);
INSERT INTO `wp_hfcm_scripts` VALUES('2', 'CopeCart Upsell Script - Body', '<script>copecartUpsell.run();</script>\r\n', 'both', 'after_content', 's_pages', '5', '[2305]', '[]', '[]', '[]', '[]', '[]', '[]', 'inactive', 'Juliusmiribung', NULL, '2020-01-13 08:26:49', NULL);
/*!40000 ALTER TABLE `wp_hfcm_scripts` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
