CREATE TABLE `wp_lms_resource` (  `r_id` int(11) NOT NULL AUTO_INCREMENT,  `post_id` int(11) NOT NULL,  `att_id` int(11) NOT NULL,  `r_link` text NOT NULL,  PRIMARY KEY (`r_id`)) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_lms_resource` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_lms_resource` VALUES('2', '107', '0', '{\"name\":\"Google\",\"url\":\"https:\\/\\/www.google.com\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('3', '107', '76', '');
INSERT INTO `wp_lms_resource` VALUES('6', '112', '0', '{\"name\":\"Amazon\",\"url\":\"https:\\/\\/www.amazon.de\\/\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('7', '112', '0', '{\"name\":\"Google\",\"url\":\"https:\\/\\/www.google.com\\/\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('8', '112', '0', '{\"name\":\"ORF\",\"url\":\"https:\\/\\/orf.at\\/\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('9', '113', '0', '{\"name\":\"Sky Sport\",\"url\":\"https:\\/\\/sport.sky.it\\/\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('10', '109', '0', '{\"name\":\"Test Link\",\"url\":\"https:\\/\\/google.de\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('11', '109', '110', '');
INSERT INTO `wp_lms_resource` VALUES('12', '109', '110', '');
INSERT INTO `wp_lms_resource` VALUES('13', '138', '0', '{\"name\":\"Udemy\",\"url\":\"https:\\/\\/www.udemy.com\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('14', '297', '0', '{\"name\":\"Google\",\"url\":\"http:\\/\\/www.google.com\"}');
INSERT INTO `wp_lms_resource` VALUES('15', '297', '0', '{\"name\":\"Vimeo\",\"url\":\"http:\\/\\/www.vimeo.com\"}');
INSERT INTO `wp_lms_resource` VALUES('16', '300', '0', '{\"name\":\"Youtube Link 1\",\"url\":\"http:\\/\\/www.youtube.com\\/123\"}');
INSERT INTO `wp_lms_resource` VALUES('17', '300', '0', '{\"name\":\"Youtube Link 2\",\"url\":\"http:\\/\\/www.youtube.com\\/456\"}');
INSERT INTO `wp_lms_resource` VALUES('18', '304', '0', '{\"name\":\"Google\",\"url\":\"http:\\/\\/www.google.com\"}');
INSERT INTO `wp_lms_resource` VALUES('19', '304', '0', '{\"name\":\"Vimeo\",\"url\":\"http:\\/\\/www.vimeo.com\"}');
INSERT INTO `wp_lms_resource` VALUES('20', '309', '0', '{\"name\":\"new test\",\"url\":\"https:\\/\\/google.de\",\"open_in_new_tab\":\"yes\"}');
INSERT INTO `wp_lms_resource` VALUES('21', '309', '0', '{\"name\":\"New test 2\",\"url\":\"https:\\/\\/orf.at\",\"open_in_new_tab\":\"yes\"}');
/*!40000 ALTER TABLE `wp_lms_resource` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
