CREATE TABLE `wp_lms_user_lesson_complete_mapping` (  `m_id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `l_id` int(11) NOT NULL,  PRIMARY KEY (`m_id`)) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_lms_user_lesson_complete_mapping` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('1', '1', '8');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('2', '1', '10');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('3', '1', '19');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('4', '2', '8');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('5', '2', '10');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('6', '2', '12');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('7', '2', '13');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('8', '2', '19');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('9', '2', '20');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('10', '1', '11');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('11', '1', '12');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('12', '1', '140');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('13', '1', '13');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('14', '6', '8');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('16', '1', '146');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('17', '1', '148');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('18', '1', '147');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('19', '1', '184');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('20', '1', '185');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('21', '1', '130');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('22', '2', '140');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('23', '2', '144');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('24', '2', '146');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('25', '2', '147');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('26', '2', '184');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('27', '2', '202');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('28', '1', '20');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('29', '1', '21');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('30', '1', '225');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('31', '1', '3284');
INSERT INTO `wp_lms_user_lesson_complete_mapping` VALUES('32', '1', '188');
/*!40000 ALTER TABLE `wp_lms_user_lesson_complete_mapping` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
