CREATE TABLE `wp_lms_section` (  `s_id` int(11) NOT NULL AUTO_INCREMENT,  `c_id` int(11) NOT NULL,  `s_name` varchar(255) NOT NULL,  PRIMARY KEY (`s_id`)) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_lms_section` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_lms_section` VALUES('1', '7', 'Section 1');
INSERT INTO `wp_lms_section` VALUES('2', '7', 'Section 2');
INSERT INTO `wp_lms_section` VALUES('3', '7', 'Section 3');
INSERT INTO `wp_lms_section` VALUES('5', '22', 'Section 1');
INSERT INTO `wp_lms_section` VALUES('6', '18', 'Section 1');
INSERT INTO `wp_lms_section` VALUES('7', '7', 'Test');
INSERT INTO `wp_lms_section` VALUES('8', '18', 'One');
INSERT INTO `wp_lms_section` VALUES('9', '121', 'New');
INSERT INTO `wp_lms_section` VALUES('10', '201', '5 - Section one');
INSERT INTO `wp_lms_section` VALUES('11', '216', 'test sectio');
INSERT INTO `wp_lms_section` VALUES('12', '295', 'Day 1 to Day 7');
INSERT INTO `wp_lms_section` VALUES('13', '295', 'Day 8 to Day 10');
INSERT INTO `wp_lms_section` VALUES('14', '295', 'Day 11 to Day 12');
INSERT INTO `wp_lms_section` VALUES('15', '302', 'Day 1 to Day 7');
INSERT INTO `wp_lms_section` VALUES('16', '302', 'Day 8 to Day 10');
INSERT INTO `wp_lms_section` VALUES('17', '302', 'Day 11 to Day 12');
/*!40000 ALTER TABLE `wp_lms_section` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
