CREATE TABLE `wp_lms_frmt_quiz_data` (  `log_id` int(11) NOT NULL AUTO_INCREMENT,  `entry_id` int(11) NOT NULL,  `l_id` int(11) NOT NULL,  `user_id` int(11) NOT NULL,  PRIMARY KEY (`log_id`)) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_lms_frmt_quiz_data` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('1', '38', '11', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('2', '39', '11', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('3', '40', '147', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('4', '41', '20', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('5', '42', '20', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('6', '46', '148', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('7', '47', '185', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('8', '48', '185', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('9', '49', '8', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('10', '50', '20', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('11', '51', '140', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('12', '52', '140', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('13', '53', '147', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('14', '54', '146', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('15', '55', '8', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('16', '56', '11', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('17', '57', '185', '2');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('18', '58', '140', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('19', '59', '20', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('20', '60', '8', '1');
INSERT INTO `wp_lms_frmt_quiz_data` VALUES('21', '61', '8', '1');
/*!40000 ALTER TABLE `wp_lms_frmt_quiz_data` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
