CREATE TABLE `wp_tg_lesson_mapping` (  `m_id` int(11) NOT NULL AUTO_INCREMENT,  `c_id` int(11) NOT NULL,  `l_id` int(11) NOT NULL,  `m_type` enum('lesson','section') NOT NULL,  `s_id` int(11) NOT NULL,  `m_order` int(5) NOT NULL,  `l_delay_type` varchar(10) NOT NULL,  `l_delay` int(3) NOT NULL,  `l_delay_date` varchar(50) NOT NULL,  `l_free` enum('No','Yes') NOT NULL,  PRIMARY KEY (`m_id`)) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_tg_lesson_mapping` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_tg_lesson_mapping` VALUES('4', '4053', '0', 'section', '0', '1', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('5', '4053', '4054', 'lesson', '0', '1', 'date', '0', '2020-07-25', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('6', '4053', '4055', 'lesson', '0', '2', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('84', '4058', '0', 'section', '0', '1', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('85', '4058', '0', 'section', '1', '1', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('86', '4058', '4063', 'lesson', '1', '1', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('87', '4058', '4075', 'lesson', '1', '2', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('88', '4058', '0', 'section', '2', '3', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('89', '4058', '4076', 'lesson', '2', '3', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('90', '4058', '4077', 'lesson', '2', '4', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('91', '4058', '4078', 'lesson', '2', '5', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('99', '4093', '0', 'section', '0', '1', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('100', '4093', '0', 'section', '3', '1', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('101', '4093', '4095', 'lesson', '3', '1', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('102', '4093', '4097', 'lesson', '3', '2', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('103', '4093', '0', 'section', '4', '3', '', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('104', '4093', '4099', 'lesson', '4', '3', 'days', '0', '', 'No');
INSERT INTO `wp_tg_lesson_mapping` VALUES('105', '4093', '4101', 'lesson', '4', '4', 'days', '0', '', 'No');
/*!40000 ALTER TABLE `wp_tg_lesson_mapping` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
