CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('3', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('4', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('5', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('6', 'exclude-from-search', 'exclude-from-search', '0');
INSERT INTO `wp_terms` VALUES('7', 'exclude-from-catalog', 'exclude-from-catalog', '0');
INSERT INTO `wp_terms` VALUES('8', 'featured', 'featured', '0');
INSERT INTO `wp_terms` VALUES('9', 'outofstock', 'outofstock', '0');
INSERT INTO `wp_terms` VALUES('10', 'rated-1', 'rated-1', '0');
INSERT INTO `wp_terms` VALUES('11', 'rated-2', 'rated-2', '0');
INSERT INTO `wp_terms` VALUES('12', 'rated-3', 'rated-3', '0');
INSERT INTO `wp_terms` VALUES('13', 'rated-4', 'rated-4', '0');
INSERT INTO `wp_terms` VALUES('14', 'rated-5', 'rated-5', '0');
INSERT INTO `wp_terms` VALUES('15', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('16', 'Landing', 'landing', '0');
INSERT INTO `wp_terms` VALUES('17', 'Checkout', 'checkout', '0');
INSERT INTO `wp_terms` VALUES('18', 'Thank You', 'thankyou', '0');
INSERT INTO `wp_terms` VALUES('19', 'Upsell', 'upsell', '0');
INSERT INTO `wp_terms` VALUES('20', 'Downsell', 'downsell', '0');
INSERT INTO `wp_terms` VALUES('21', 'flow-70', 'flow-70', '0');
INSERT INTO `wp_terms` VALUES('22', 'Headers', 'headers', '0');
INSERT INTO `wp_terms` VALUES('23', 'Footers', 'footers', '0');
INSERT INTO `wp_terms` VALUES('24', 'flow-250', 'flow-250', '0');
INSERT INTO `wp_terms` VALUES('25', 'flow-282', 'flow-282', '0');
INSERT INTO `wp_terms` VALUES('26', 'nav', 'nav', '0');
INSERT INTO `wp_terms` VALUES('27', 'Fitness', 'fitness', '0');
INSERT INTO `wp_terms` VALUES('28', 'Business', 'business', '0');
INSERT INTO `wp_terms` VALUES('29', 'Fun', 'fun', '0');
INSERT INTO `wp_terms` VALUES('30', 'woocommerce-db-updates', 'woocommerce-db-updates', '0');
INSERT INTO `wp_terms` VALUES('31', 'wc-admin-notes', 'wc-admin-notes', '0');
INSERT INTO `wp_terms` VALUES('32', 'wc_update_product_lookup_tables', 'wc_update_product_lookup_tables', '0');
INSERT INTO `wp_terms` VALUES('33', 'wc-admin-data', 'wc-admin-data', '0');
INSERT INTO `wp_terms` VALUES('34', 'Optin (Woo)', 'optin', '0');
INSERT INTO `wp_terms` VALUES('35', 'page', 'page', '0');
INSERT INTO `wp_terms` VALUES('36', 'single', 'single', '0');
INSERT INTO `wp_terms` VALUES('37', 'Category ONE', 'category-one', '0');
INSERT INTO `wp_terms` VALUES('38', 'Category TWO', 'category-two', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
