CREATE TABLE `wp_tg_frmt_quiz_data` (  `log_id` int(11) NOT NULL AUTO_INCREMENT,  `entry_id` int(11) NOT NULL,  `l_id` int(11) NOT NULL,  `user_id` int(11) NOT NULL,  PRIMARY KEY (`log_id`)) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_tg_frmt_quiz_data` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('1', '62', '4099', '1');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('2', '63', '4099', '0');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('3', '64', '4099', '1');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('4', '65', '4099', '1');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('5', '66', '4099', '1');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('6', '67', '4099', '1');
INSERT INTO `wp_tg_frmt_quiz_data` VALUES('7', '68', '4099', '1');
/*!40000 ALTER TABLE `wp_tg_frmt_quiz_data` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
