CREATE TABLE `wp_wc_admin_note_actions` (  `action_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `note_id` bigint(20) unsigned NOT NULL,  `name` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `label` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `query` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,  `status` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `is_primary` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`action_id`),  KEY `note_id` (`note_id`)) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_wc_admin_note_actions` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_wc_admin_note_actions` VALUES('1', '1', 'learn-more', 'Learn more', 'https://woocommerce.wordpress.com/', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('2', '2', 'connect', 'Connect', '?page=wc-addons&section=helper', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('3', '3', 'learn-more', 'Learn more', 'https://woocommerce.com/mobile/', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('4', '4', 'share-feedback', 'Review', 'https://wordpress.org/support/plugin/woocommerce-admin/reviews/?rate=5#new-post', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('5', '5', 'learn-more', 'Learn more', 'https://woocommerce.com/products/facebook/', 'unactioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('6', '5', 'install-now', 'Install now', '', 'actioned', '1');
INSERT INTO `wp_wc_admin_note_actions` VALUES('7', '6', 'tracking-dismiss', 'Dismiss', '', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('8', '6', 'tracking-opt-in', 'Activate usage tracking', '', 'actioned', '1');
INSERT INTO `wp_wc_admin_note_actions` VALUES('9', '7', 'learn-more', 'Learn more', 'https://docs.woocommerce.com/document/managing-orders/', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('10', '8', 'view-report', 'View report', '?page=wc-admin&path=/analytics/revenue&period=custom&compare=previous_year&after=2019-12-06&before=2019-12-06', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('11', '9', 'open-customizer', 'Open Customizer', 'customize.php', 'actioned', '0');
INSERT INTO `wp_wc_admin_note_actions` VALUES('12', '10', 'yes-please', 'Yes please!', 'https://woocommerce.us8.list-manage.com/subscribe/post?u=2c1434dc56f9506bf3c3ecd21&amp;id=13860df971&amp;SIGNUPPAGE=plugin', 'actioned', '0');
/*!40000 ALTER TABLE `wp_wc_admin_note_actions` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
